import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navabar";

export const poppinsFont = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin", "latin-ext"],
  variable: "--poppins-font",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={poppinsFont.className}
      ><Navbar/>
        {children}
      </body>
    </html>
  );
}
